version: '2'

services:
  app:
    volumes:
      - .:/app
      - bundler-data:/bundle
      - /bundle:/bundle
      - ssh-data:/ssh:ro

volumes:
  ssh-data:
    external:
      name: ssh_data

  bundler-data:
    external:
      name: bundler_data
